name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.x'

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Check if webserver can run, then terminate if not error
      run: |
        uvicorn app:app --port 8000 --reload &
    
    - name: Test webserver
      run: |
        sleep 15
        curl -f http://127.0.0.1:8000 || exit 1
    
    - name: Stop webserver
      run: |
        pkill -f "uvicorn app:app"